language: node_js
node_js:
- 6
- 7
cache: yarn
script:
- yarn run eslint
- yarn run cover
deploy:
  provider: npm
  email: joe.grund@intel.com
  api_key:
    secure: K5JqjZxb2IjPS9K6qZO471cpy1kgeNabWLtCcMwnWfRiNORDlQ1tSclSEqoR64E8sUMv6xSXVIkiHmIxtKWXSpC8dN3/bBzOPyfIf81L6ZgzK2baJ7+t7NVd8FqNbYsl0eoLDFYn9wuLwhOtCLSCiidj5vOVJ8/cOhPuqHkxvuTAVp8HmiFiTKCebDwctW1LEJgi4Vdpi0pRRy5lbaKapr8KJRgs5rF6kwTIAhc8msWO8TSREfSH11frA9Mdmokmtl8cm0Gnk4ydbUkWn2iqrmq+1KgNW8eb6Jq8TinSYvKTwiV+ioA+1mGzPejpjoNDf0cBTnpBBEuK/gjbF8BQObgh/JOPrErXpMG5GaTXvzPYrKPzzq9TObk218hye8b2Tr4D8xuS2whcQbwXLh/xUwvD+6rXZyFN0TvBAjzkkUUuGA0mpybFvCkg6jN8NBqY5Ud64+fxc6kD+/0TA3gqOYvz/pQJKZkB02iX9oS0ZKoIAPpi1ztPDrXIeD8KaYCSJH8L7jA9pfjXUyqI+Qoa4cr05omVOSAesrN29WMa8chkeJzvR7DwreqqNENYMbivRXqhGqF1Abmx5huyRU2glcskiLbl87Eq8ouXa3Q/QYuTad3tgSrd57LogQDAg795K8iLHAICiZg07w3cWgXLZcaN4YPe4pUZOK/2mmSgD5E=
  on:
    tags: true
    repo: intel-hpdd/stub-daddy
